### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by yufengwhy** [Chillee/OpenReviewExplorer#1]
[Really nice work~](https://chillee.github.io/OpenReviewExplorer/)
How about generalize this work to other conference, such as KDD, ACL, CVPR ...
Given abstract and link of paper, readers can comment and vote, then we can rerank and group the paper list for better reading and discussion?

**Comment by Chillee** [comment]
I'd love to. However, a lot of these other conferences don't provide reviews for the papers. I think NIPS is possible, however, they don't provide quantitative scores for each paper, just qualitative ones.
