### ISSUE TITLE
Clicking on 'charts' from homepage shows ICLR2018

### ISSUE THREAD

**Issue by wouterkool** [Chillee/OpenReviewExplorer#3]
Hi,

I like this tool very much, great job! I have one minor comment though which may be helpful: if you just go to [https://chillee.github.io/OpenReviewExplorer/](https://chillee.github.io/OpenReviewExplorer/) and then click on 'Charts' you get charts for ICLR 2018, which may be easily overlooked. Maybe it would be good to link to 2019? Or add the year in the chart titles such that it cannot be overlooked.

**Comment by Chillee** [comment]
Oh jeez. The hardcoding I made when I initially hacked this up are starting to come back and haunt me.

Thanks for the heads up, I'll abstract this properly so this won't happen again.

**Comment by Chillee** [comment]
Should be fixed (although I haven't abstracted it...)
